### ISSUE TITLE
Cannot resolve `dummy.js`

### ISSUE THREAD

**Issue by Ethan-Arrowood** [opennextjs/opennextjs-aws#636]
I'm trying to use OpenNext with the following configuration: 

```js
export default {
	default: {
		override: {
			wrapper: 'node',
			converter: 'node',
			incrementalCache: 'dummy',
			tagCache: 'dummy',
			queue: 'dummy'
		},
	}
};
```

But when I run the build I get: 
```
❯ npx open-next build                               
Next.js version : 14.2.5
OpenNext v3.1.3

┌─────────────────────────────────┐
│ OpenNext — Building Next.js app │
└─────────────────────────────────┘


> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.5

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    5.42 kB        92.5 kB
└ ○ /_not-found                          871 B          87.9 kB
+ First Load JS shared by all            87 kB
  ├ chunks/23-b75664ace61c0abb.js        31.5 kB
  ├ chunks/fd9d1056-2821b0f0cabcd8bd.js  53.6 kB
  └ other shared chunks (total)          1.87 kB


○  (Static)  prerendered as static content


┌──────────────────────────────┐
│ OpenNext — Generating bundle │
└──────────────────────────────┘

Bundling middleware function...
Bundling static assets...
Bundling cache assets...
Building server function: default...
✘ [ERROR] Could not resolve "../cache/tag/dummy.js"

    node_modules/open-next/dist/core/resolve.js:34:33:
      34 │         const m_1 = await import("../cache/tag/dummy.js");
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../queue/dummy.js"

    node_modules/open-next/dist/core/resolve.js:49:33:
      49 │         const m_1 = await import("../queue/dummy.js");
         ╵                                  ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../cache/incremental/dummy.js"

    node_modules/open-next/dist/core/resolve.js:64:33:
      64 │         const m_1 = await import("../cache/incremental/dummy.js");
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1649
  let error = new Error(text);
              ^

Error: Build failed with 3 errors:
node_modules/open-next/dist/core/resolve.js:34:33: ERROR: Could not resolve "../cache/tag/dummy.js"
node_modules/open-next/dist/core/resolve.js:49:33: ERROR: Could not resolve "../queue/dummy.js"
node_modules/open-next/dist/core/resolve.js:64:33: ERROR: Could not resolve "../cache/incremental/dummy.js"
    at failureErrorWithLog (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/ethan/dev/testing/my-app/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.16.0
```

**Comment by sommeeeer** [comment]
this is probably related to version, can you try doing `npx @opennextjs/aws build` instead?

**Comment by conico974** [comment]
Yeah the dummy adapter has been added in 3.2.0.
BTW setting this to dummy will make both ISR and SSG not work

**Comment by Ethan-Arrowood** [comment]
Ah okay that makes more sense. I was using `open-next@latest` which looks to be `3.1.3` currently. All good, thanks for the help!
